### ISSUE TITLE
[BUG] Databricks 9.1ML failed with "java.lang.NoSuchMethodError: org.apache.spark.sql.execution.metric.SQLMetrics$.createSizeMetric"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5164]
When testing sample queries on Databricks 9.1ML LTS with Spark RAPIDS, query failed with:
```
NoSuchMethodError: org.apache.spark.sql.execution.metric.SQLMetrics$.createSizeMetric(Lorg/apache/spark/SparkContext;Ljava/lang/String;)Lorg/apache/spark/sql/execution/metric/SQLMetric;

at com.nvidia.spark.rapids.GpuExec.$anonfun$createSizeMetric$1(GpuExec.scala:260)
	at com.nvidia.spark.rapids.GpuExec.createMetricInternal(GpuExec.scala:247)
	at com.nvidia.spark.rapids.GpuExec.createSizeMetric(GpuExec.scala:260)
	at com.nvidia.spark.rapids.GpuExec.createSizeMetric$(GpuExec.scala:259)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec.createSizeMetric(GpuFileSourceScanExec.scala:63)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec.allMetrics$lzycompute(GpuFileSourceScanExec.scala:374)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec.allMetrics(GpuFileSourceScanExec.scala:402)
	at com.nvidia.spark.rapids.GpuExec.metrics(GpuExec.scala:280)
	at com.nvidia.spark.rapids.GpuExec.metrics$(GpuExec.scala:280)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec.metrics$lzycompute(GpuFileSourceScanExec.scala:63)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec.metrics(GpuFileSourceScanExec.scala:63)
	at org.apache.spark.sql.execution.SparkPlanInfo$.fromSparkPlan(SparkPlanInfo.scala:85)
	at org.apache.spark.sql.execution.SparkPlanInfo$.$anonfun$fromSparkPlan$4(SparkPlanInfo.scala:113)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.SparkPlanInfo$.fromSparkPlan(SparkPlanInfo.scala:113)
	at org.apache.spark.sql.execution.SparkPlanInfo$.$anonfun$fromSparkPlan$4(SparkPlanInfo.scala:113)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.SparkPlanInfo$.fromSparkPlan(SparkPlanInfo.scala:113)
	at org.apache.spark.sql.execution.SparkPlanInfo$.fromSparkPlan(SparkPlanInfo.scala:70)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:126)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:273)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:223)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3823)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2972)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:317)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:354)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:850)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:809)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:818)
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>([command-3226453300435722:2]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw$$iw$$iw$$iw$$iw.<init>([command-3226453300435722:49]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw$$iw$$iw$$iw.<init>([command-3226453300435722:51]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw$$iw$$iw.<init>([command-3226453300435722:53]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw$$iw.<init>([command-3226453300435722:55]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$$iw.<init>([command-3226453300435722:57]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read.<init>([command-3226453300435722:59]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$.<init>([command-3226453300435722:63]())
	at $linef94a3931a1e047819599fd4a85292d5b31.$read$.<clinit>(command-3226453300435722)
	at $linef94a3931a1e047819599fd4a85292d5b31.$eval$.$print$lzycompute(<notebook>:7)
	at $linef94a3931a1e047819599fd4a85292d5b31.$eval$.$print(<notebook>:6)
	at $linef94a3931a1e047819599fd4a85292d5b31.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:887)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:840)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:235)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:526)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:266)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:50)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:305)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:297)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:50)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:503)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:611)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:603)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:522)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:557)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:427)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:370)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:221)
	at java.lang.Thread.run(Thread.java:748)
```

Env:
22.02GA release jar
or 
22.04 snapshot jar

Repro query:
```
val df=spark.read.csv("abfss://containerf...dfs.core.windows.net/sample.csv")
df.show()
```

**Comment by jlowe** [comment]
Databricks 9.1 premerge builds and tests are passing, so I suspect an interface changed in a source-compatible but not binary-compatible way.  That would explain why fresh code is working yet older builds do not.  We need to rebuild against the updated Databricks 9.1 code to fix.

**Comment by tgravescs** [comment]
tested rebuilt jar that includes fix https://github.com/NVIDIA/spark-rapids/pull/5165 on both 10.4 and 9.1 and it is working.  The fix for https://github.com/NVIDIA/spark-rapids/pull/5165 is specifically 10.4 and this error went away with the rebuild.

**Comment by tgravescs** [comment]
as mentioned above this was fixed by recompile so closing

**Comment by mickvanhulst-TomTom** [comment]
@tgravescs I, unfortunately, still have this issue? I followed the tutorial for Databricks (see: https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/docs/get-started/getting-started-databricks.md), but am unfortunately still getting the same error (both for runtime 10.4 and 9.1). 

Any details you can share related to what resulted in what steps I can take to mitigate this (perhaps create a separate ticket if needed)? I ran the example notebook (https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/docs/demo/gpu-mortgage_accelerated.ipynb) and I experience the same error as stated above when executing the following line:

```
acq.repartition(12).write.parquet(tmp_acq_path, mode='overwrite')
```

**Comment by tgravescs** [comment]
@mickvanhulst-TomTom  what jar were you running with?   We don't publish 22.06 jars and we haven't published the fixed 22.04 jars so did you build it yourself on Databricks?  

The way this is fixed is by rebuilding of the plugin code against the latest databricks version.
Let me know and happy to help figure out what is going on.  If it is easier you could start a discussion thread at https://github.com/NVIDIA/spark-rapids/discussions

**Comment by mickvanhulst-TomTom** [comment]
Aha I see, I will try building it against the latest Databricks version then. If that does not work, I will start a discussion thread as you mentioned. Thanks a lot for the fast reply :)!
